---
- name: Install packages for BeeGFS client
  package:
    name: "{{ item }}"
    state: "{{ beegfs_package_action }}"
  with_items:
    - beegfs-client
    - beegfs-helperd
    - beegfs-utils
  become: true
  notify: Restart BeeGFS client service

- name: Ensure kernel development headers are present
  package:
    name: "{{ beegfs_distro_vars[ansible_os_family]['kernel_dev_pkg'] }}-{{ ansible_kernel }}"
    state: present
  notify: Restart BeeGFS client service
  become: true

- name: Ensure the BeeGFS mount point exists
  file:
    path: "{{ client_path }}"
    state: directory
  become: true
  notify: Restart BeeGFS client service

- name: Run client service setup script
  command: "/opt/beegfs/sbin/beegfs-setup-client -m {{ client_mgmt_host }}"
  args:
    creates: "{{ beegfs_kernel_module }}"
  become: true
  notify: Restart BeeGFS client service

- name: Copy connAuthFile from first master server (mgmt)
  synchronize:
    mode: push
    src: "{{ beegfs_connauthfile_path }}"
    dest: "{{ beegfs_connauthfile_path }}"
  delegate_to: "{{ groups['master'][0] }}"
  become: true

- name: Specify connAuthFile
  lineinfile:
    path: /etc/beegfs/beegfs-client.conf
    regexp: "^connAuthFile"
    line: "connAuthFile           = {{ beegfs_connauthfile_path }}"
  become: true
  notify: Restart BeeGFS client service
...
