---
- name: Install packages for BeeGFS metadata server
  package:
    name: beegfs-meta
    state: "{{ beegfs_package_action }}"
  become: true
  notify: Restart BeeGFS meta service

- name: Create directory for BeeGFS metadata
  file:
    path: "{{ beegfs_meta_path }}"
    state: directory
  become: true
  notify: Restart BeeGFS meta service

- name: Prepare metadata block storage
  block:
    - name: Ensure storage device is not currently mounted
      mount:
        path: "{{ beegfs_meta.path }}"
        state: unmounted
      notify: Restart BeeGFS meta service
    - name: Format filesystem
      vars:
        meta_fstype: "{{ beegfs_meta.fstype | default(beegfs_meta.fstype) }}"
      filesystem:
        dev: "{{ beegfs_meta.dev }}"
        fstype: "{{ meta_fstype }}"
        force: "{{ beegfs_force_format }}"
      notify: Restart BeeGFS meta service
    - name: Mount filesystem
      vars:
        meta_fstype: "{{ beegfs_meta.fstype | default(beegfs_meta.fstype) }}"
      mount:
        src: "{{ beegfs_meta.dev }}"
        path: "{{ beegfs_meta.path }}"
        fstype: "{{ meta_fstype }}"
        state: mounted
      notify: Restart BeeGFS meta service
  become: true
  when:
    - beegfs_meta.dev is defined
    - beegfs_meta.dev != None

- name: Run metadata service setup script
  command: "/opt/beegfs/sbin/beegfs-setup-meta -p {{ beegfs_meta.path }} -m {{ beegfs_mgmt_host }} -f"
  args:
    creates: "{{ beegfs_meta.path }}/originalNodeID"
  become: true
  notify: Restart BeeGFS meta service

- name: Specify connInterfacesFile
  lineinfile:
    path: /etc/beegfs/beegfs-meta.conf
    regexp: "^connInterfacesFile"
    line: "connInterfacesFile           = /etc/beegfs/connInterfacesFile"
  become: true
  notify: Restart BeeGFS meta service
...
