---
- name: Install packages for BeeGFS management server
  package:
    name: beegfs-mgmtd
    state: "{{ beegfs_package_action }}"
  become: true
  notify: Restart BeeGFS mgmt service

- name: Create directory for BeeGFS management service data
  file:
    path: "{{ beegfs_mgmt_path }}"
    state: directory
  become: true
  notify: Restart BeeGFS mgmt service

- name: Run management service setup script
  command: 
    cmd: "/opt/beegfs/sbin/beegfs-setup-mgmtd -p {{ beegfs_mgmt_path }} -f"
    creates: "{{ beegfs_mgmt_path }}/originalNodeID"
  become: true
  notify: Restart BeeGFS mgmt service

- name: Create connAuthFile
  command: 
    cmd: "dd if=/dev/random of={{ beegfs_connauthfile_path }} bs=128 count=1"
    creates: "{{ beegfs_connauthfile_path }}"
  
- name: Specify connAuthFile
  lineinfile:
    path: /etc/beegfs/beegfs-mgmtd.conf
    regexp: "^connAuthFile"
    line: "connAuthFile           = {{ beegfs_connauthfile_path }}"
  become: true
  notify: Restart BeeGFS mgmt service


- name: Enable quota enforcement
  lineinfile:
    path: "/etc/beegfs/beegfs-mgmtd.conf"
    regexp: "^quotaEnableEnforcement"
    insertafter: "^logType"
    line: "quotaEnableEnforcement           = true"
  become: true
  notify: Restart BeeGFS mgmt service
...
